export const dashboardStats = [
  {
    id: 'new-apps',
    title: 'New Applications',
    value: '18',
    description: 'Requires Verification',
    trend: '+12% vs last week',
    trendDirection: 'up',
    variant: 'info',
  },
  {
    id: 'pending-verif',
    title: 'Pending Verification',
    value: '7',
    description: 'In Progress',
    trend: '3 urgent calls',
    trendDirection: 'neutral',
    variant: 'warning',
  },
  {
    id: 'approved-apps',
    title: 'Approved Loans',
    value: '42',
    description: 'This Month',
    trend: '+18% vs last month',
    trendDirection: 'up',
    variant: 'success',
  },
  {
    id: 'total-agents',
    title: 'Active Agents',
    value: '14',
    description: 'Reporting to RM',
    trend: '92% active today',
    trendDirection: 'up',
    variant: 'default',
  },
];

export const recentApplicationsData = [
  {
    id: 'APP-2024-001',
    customerName: 'Ramesh Kumar',
    mobile: '98765 43210',
    loanType: 'Business Expansion',
    amount: '₹1,50,000',
    agentName: 'Karthik Raja',
    createdDate: '05 Jun 2025',
    status: 'Pending Verification',
  },
  {
    id: 'APP-2024-002',
    customerName: 'Priya Sundaram',
    mobile: '98401 12345',
    loanType: 'Personal Loan',
    amount: '₹75,000',
    agentName: 'Venkatesh S',
    createdDate: '05 Jun 2025',
    status: 'New',
  },
  {
    id: 'APP-2024-003',
    customerName: 'Anand Verma',
    mobile: '97100 88990',
    loanType: 'Micro Loan',
    amount: '₹50,000',
    agentName: 'Karthik Raja',
    createdDate: '04 Jun 2025',
    status: 'Under Review',
  },
  {
    id: 'APP-2024-004',
    customerName: 'Lakshmi Narayanan',
    mobile: '99402 33445',
    loanType: 'Business Expansion',
    amount: '₹2,00,000',
    agentName: 'Saravanan M',
    createdDate: '03 Jun 2025',
    status: 'Approved',
  },
  {
    id: 'APP-2024-005',
    customerName: 'Dinesh Karthik',
    mobile: '98840 55667',
    loanType: 'Emergency Credit',
    amount: '₹40,000',
    agentName: 'Venkatesh S',
    createdDate: '02 Jun 2025',
    status: 'Returned',
  },
];

export const agentPerformanceData = [
  { name: 'Karthik Raja', totalCustomers: 45, pendingVerification: 3, submitted: 38, activeCustomers: 32, pendingCollection: '₹14,500' },
  { name: 'Venkatesh S', totalCustomers: 38, pendingVerification: 2, submitted: 32, activeCustomers: 28, pendingCollection: '₹8,200' },
  { name: 'Saravanan M', totalCustomers: 29, pendingVerification: 1, submitted: 25, activeCustomers: 22, pendingCollection: '₹19,800' },
  { name: 'Divya Bharathi', totalCustomers: 34, pendingVerification: 0, submitted: 31, activeCustomers: 29, pendingCollection: '₹4,300' },
  { name: 'Manikandan P', totalCustomers: 22, pendingVerification: 1, submitted: 19, activeCustomers: 15, pendingCollection: '₹11,000' },
];

export const statusSummaryData = [
  { label: 'New', value: 35, percent: 19, color: '#0284C7' },
  { label: 'Pending Verification', value: 28, percent: 15, color: '#F59E0B' },
  { label: 'Under Review', value: 45, percent: 25, color: '#A855F7' },
  { label: 'Approved', value: 58, percent: 32, color: '#22C55E' },
  { label: 'Returned', value: 16, percent: 9, color: '#EF4444' },
];
